services:
  inspircd:
    image: inspircd/inspircd-docker:latest
    container_name: inspircd
    restart: unless-stopped
    ports:
      - "6667:6667"
    volumes:
      - ./inspircd/etc/inspircd:/inspircd/conf:ro
    networks:
      - royal-family

  ollama:
    image: ollama/ollama:rocm
    container_name: ollama
    restart: unless-stopped
    ports:
      - "11434:11434"
    volumes:
      - ollama-data:/root/.ollama
    devices:
      - /dev/kfd
      - /dev/dri
    networks:
      - royal-family

volumes:
  ollama-data:

networks:
  royal-family:
    name: royal-family
    driver: bridge
