#!/usr/bin/env bash
# Create a training signal PR: debate transcript + Hindsight patterns + confidence scores + diff.
# merge=positive RL signal, close=negative RL signal.
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "$0")/.." && pwd)"
DEBATES_DIR="${DEBATES_DIR:-$REPO_ROOT/debates}"
DEBATE_RECORD="${DEBATE_RECORD:-$(ls -t "$DEBATES_DIR"/*.md 2>/dev/null | head -1)}"
CONFIDENCE_SCORES="${CONFIDENCE_SCORES:-0.50}"
ISSUE_URL="${ISSUE_URL:-}"
DRY_RUN="${DRY_RUN:-false}"

if [[ -z "$DEBATE_RECORD" ]] || [[ ! -f "$DEBATE_RECORD" ]]; then
  echo "[training-pr] ERROR: no debate record found in $DEBATES_DIR"
  exit 1
fi

ISSUE_SLUG=$(grep "^issue_slug:" "$DEBATE_RECORD" | awk '{print $2}')
DATE=$(grep "^date:" "$DEBATE_RECORD" | awk '{print $2}')
CONFIDENCE=$(grep "^confidence:" "$DEBATE_RECORD" | awk '{print $2}')

# Collect Hindsight patterns (graceful fallback if server unavailable)
HINDSIGHT_URL="${HINDSIGHT_MCP_URL:-http://localhost:8888}"
HINDSIGHT_SECTION=""
if [[ "$DRY_RUN" != "true" ]]; then
  HINDSIGHT_SECTION=$(curl -sf "$HINDSIGHT_URL/reflect" \
    -H "Content-Type: application/json" \
    -d "{\"query\":\"$ISSUE_SLUG\",\"bank_id\":\"shared\"}" \
    2>/dev/null | python3 -c 'import json,sys; d=json.load(sys.stdin); print(d.get("patterns",""))' \
    2>/dev/null || echo "")
fi

# Git diff since branch diverged
DIFF=$(git -C "$REPO_ROOT" diff main...HEAD 2>/dev/null | head -200 || echo "no diff")

DEBATE_BODY=$(cat "$DEBATE_RECORD")

PR_TITLE="training: ${ISSUE_SLUG} (confidence: ${CONFIDENCE})"

PR_BODY="## Debate Transcript

\`\`\`
$DEBATE_BODY
\`\`\`

## Hindsight: Patterns

${HINDSIGHT_SECTION:-_No hindsight patterns available_}

## Confidence Scores

Runs: ${CONFIDENCE_SCORES}
Final: ${CONFIDENCE}
$(if python3 -c "exit(0 if float('${CONFIDENCE}') < 0.75 else 1)" 2>/dev/null; then
  echo "Label: needs-help (confidence < 0.75 — consider manual escalation)"
else
  echo "Label: auto-passed (confidence >= 0.75)"
fi)

## Implementation Diff

\`\`\`diff
$DIFF
\`\`\`

---
Issue: ${ISSUE_URL:-unknown}
Date: ${DATE}
🤖 Generated by ralph loop — merge=positive signal, close=negative signal"

if [[ "$DRY_RUN" == "true" ]]; then
  echo "[training-pr] DRY RUN — PR body preview:"
  echo "$PR_BODY" | head -20
  gh pr create --title "$PR_TITLE" --body "$PR_BODY" 2>/dev/null || echo "[training-pr] gh stub invoked"
  exit 0
fi

gh pr create --title "$PR_TITLE" --body "$PR_BODY"
echo "[training-pr] PR created for $ISSUE_SLUG"
